export const POPULAR_LOCATIONS = [
  "New York, NY",
  "Los Angeles, CA",
  "San Francisco, CA",
  "Miami, FL",
  "Chicago, IL",
  "Las Vegas, NV",
  "Seattle, WA",
  "Boston, MA",
  "Austin, TX",
  "Denver, CO",
  "Nashville, TN",
  "New Orleans, LA",
  "Portland, OR",
  "Washington, DC",
  "San Diego, CA",
  "Philadelphia, PA",
  "Atlanta, GA",
  "Dallas, TX",
  "Houston, TX",
  "Phoenix, AZ",
];